eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    instance-id: BOOKING-SERVICE


# spring:
#   application:
#     name: BOOKING-SERVICE